### ISSUE TITLE
ES 1.2.x and 1.3.x fails to start with amazon-s3-river installed

### ISSUE THREAD

**Issue by rotsee** [lbroudoux/es-amazon-s3-river#18]
This plugin dows not work with ES 1.2.x or 1.3.x

With 1.3.x it gives the following error:

```
 VerifyError[class com.github.lbroudoux.elasticsearch.river.s3.rest.S3ManageAction overrides final method handleRequest.(Lorg/elasticsearch/rest/RestRequest;Lorg/elasticsearch/rest/RestChannel;)V]
```

With 1.2.x it gives :

```
ExecutionError[java.lang.NoClassDefFoundError: org/elasticsearch/rest/XContentThrowableRestResponse]
```

I didn't try 1.1
